services:
  - type: web
    name: document-management-system
    env: docker
    dockerfilePath: Dockerfile
    plan: free

    buildCommand: |
      composer install --no-dev --optimize-autoloader

      # تثبيت الموارد الأمامية إذا كانت موجودة
      yarn install || true
      yarn run build || true

      # تنظيف الكاش أولاً
      php artisan config:clear
      php artisan route:clear
      php artisan view:clear

      # إعادة توليد الكاش
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache

      # تنفيذ المايجريشن إجباريًا
      php artisan migrate --force

      # صلاحيات الملفات
      chmod -R 775 storage bootstrap/cache
      chown -R www-data:www-data storage bootstrap/cache

    startCommand: php artisan serve --host=0.0.0.0 --port=10000

    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://document-management-system.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d18k48bipnbc738t7lfg-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: doc_mang_rcx4
      - key: DB_USERNAME
        value: doc_mang_rcx4_user
      - key: DB_PASSWORD
        value: 66Em0DM2nWCG3PEqo0A5ojNrWkcZo9GH
