services:
  - type: web
    name: laravel-nginx
    env: docker
    plan: free
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: ${db.host}
      - key: DB_PORT
        value: ${db.port}
      - key: DB_DATABASE
        value: ${db.database}
      - key: DB_USERNAME
        value: ${db.username}
      - key: DB_PASSWORD
        value: ${db.password}

databases:
  - name: db
    type: mysql
    plan: free
    databaseName: laravel_nginx_db
    userName: laravel_user
