services:
  - type: web
    name: cloudprojectv2
    env: docker
    buildCommand: "composer install --no-dev --optimize-autoloader"
    startCommand: |
      cp .env.example .env && \
      php artisan key:generate && \
      php artisan migrate --force && \
      php-fpm -D && nginx -g 'daemon off;'
    healthCheckPath: /
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: ${db.host}
      - key: DB_PORT
        value: ${db.port}
      - key: DB_DATABASE
        value: ${db.database}
      - key: DB_USERNAME
        value: ${db.username}
      - key: DB_PASSWORD
        value: ${db.password}

databases:
  - name: db
    type: mysql
    plan: free
    databaseName: cloudprojectv2_db
    userName: cloudprojectv2_user
