services:
  - type: web
    name: cloudprojectv2
    env: docker
    buildCommand: >
      composer install --no-dev --optimize-autoloader
    startCommand: >
      cp .env.example .env &&
      php artisan key:generate &&
      php artisan migrate --force &&
      chmod -R 775 storage bootstrap/cache &&
      php-fpm -D && nginx -g 'daemon off;'
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d17vat3uibrs7386vhk0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: doc_mang
      - key: DB_USERNAME
        value: doc_mang_user
      - key: DB_PASSWORD
        value: JQ0k0qfROVqTrVeJvxLx5S1nwdUzk9lW
